In [1]:
import numpy as np

class Perceptron(object):

    def __init__(self, eta=0.01, n_iter=10):
        self.eta = eta
        self.n_iter = n_iter

In [2]:
def weighted_sum(self, X):
    return np.dot(X, self.w_[1:]) + self.w_[0]

In [3]:
#def predict(self, x):
    #return np.where(self.weighted_sum(x) >= 0.0, 1, -1)

def sigmoid(self, z):
    return 1 / (1 + np.exp(-z))

def predict(self, x):
    return np.where(self.sigmoid(self.weighted_sum(x)) >= 0.5, 1, 0)

In [4]:
def fit(self, X, y):
    # Initialize the weights to 0
    self.w_ = np.zeros(1 + X.shape[1])  
    self.errors_ = []  

    print("Weights initialized:", self.w_)  

    for _ in range(self.n_iter):  
        errors = 0  

        for xi, target in zip(X, y):  # Loop through each training sample and corresponding target value
            update = self.eta * (target - self.predict(xi))  # Predict the output for the current input 'xi'

            self.w_[1:] += update * xi  # Update the weights (excluding bias)
            self.w_[0] += update  # Update the bias term separately

            errors += int(update != 0.0)  # Increment the error count if the model's prediction was incorrect

        self.errors_.append(errors)  # Store the error count after each iteration

In [5]:
import pandas as pd  # For data manipulation
from sklearn.utils import shuffle  # To randomize the dataset
import numpy as np  # For numerical operations

# Load the Iris dataset from UCI repository
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)

# Shuffle the dataset to ensure random distribution
df = shuffle(df)

# Display the first few rows
df.head()

0    1    2    3                4
18   5.7  3.8  1.7  0.3      Iris-setosa
61   5.9  3.0  4.2  1.5  Iris-versicolor
145  6.7  3.0  5.2  2.3   Iris-virginica
17   5.1  3.5  1.4  0.3      Iris-setosa
140  6.7  3.1  5.6  2.4   Iris-virginica

In [7]:
# Extracting the first four columns (features) as a NumPy array
X = df.iloc[:, 0:4].values

# Extracting the fifth column (target) as a NumPy array
y = df.iloc[:, 4].values

# Displaying the first 5 rows of features and labels
print(X[0:5])
print(y[0:5])

[[5.7 3.8 1.7 0.3]
 [5.9 3.  4.2 1.5]
 [6.7 3.  5.2 2.3]
 [5.1 3.5 1.4 0.3]
 [6.7 3.1 5.6 2.4]]
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica']


In [8]:
from sklearn.model_selection import train_test_split

# Split the data: 75% for training, 25% for testing
train_data, test_data, train_labels, test_labels = train_test_split(X, y, test_size=0.25)

# Encode labels: 1 for 'Iris-setosa', -1 for all others
train_labels = np.where(train_labels == 'Iris-setosa', 1, 0)
test_labels = np.where(test_labels == 'Iris-setosa', 1, 0)

# Preview samples
print('Train data:', train_data[0:2])
print('Train labels:', train_labels[0:2])
print('Test data:', test_data[0:2])
print('Test labels:', test_labels[0:2])

Train data: [[6.2 2.2 4.5 1.5]
 [5.6 2.7 4.2 1.3]]
Train labels: [0 0]
Test data: [[6.7 2.5 5.8 1.8]
 [4.9 2.4 3.3 1. ]]
Test labels: [0 0]


In [9]:
from sklearn.linear_model import Perceptron

# Initialize the Perceptron with a learning rate and max iterations
perceptron = Perceptron(eta0=0.1, max_iter=10)

# Train the model on your preprocessed training data
perceptron.fit(train_data, train_labels)

Perceptron(eta0=0.1, max_iter=10)

In [10]:
# Predict labels for the test dataset using the trained Perceptron
#test_preds = perceptron.predict(test_data)

# Output the predicted labels
#print(test_preds)

# Manual input for prediction
manual_input = []

# Prompt user for each feature
features = ['Sepal length', 'Sepal width', 'Petal length', 'Petal width']
for feature in features:
    value = float(input(f"Enter {feature}: "))
    manual_input.append(value)

# Convert to NumPy array and reshape for prediction
manual_input = np.array(manual_input).reshape(1, -1)

# Predict using trained model
prediction = perceptron.predict(manual_input)

# Display result
if prediction[0] == 1:
    print("Prediction: Iris-setosa 🌸")
else:
    print("Prediction: Not Iris-setosa")



Prediction: Not Iris-setosa


In [11]:
from sklearn.metrics import accuracy_score

# Generate predictions
y_preds = perceptron.predict(test_data)

# Calculate accuracy
accuracy = accuracy_score(y_preds, test_labels)

# Display accuracy as a percentage
print("Accuracy:", round(accuracy, 2) * 100, "%")

Accuracy: 100.0 %
